export type MockModuleCatalogEntry = {
  moduleId: string
  friendlyName: string
  technicalName: string
  categoryCoverage: string
  subCoverage: string[]
  channelCapacity: number
  supportedSpecs: Record<string, string[]>
  protocolSupport?: string[]
}

export const MOCK_MODULE_CATALOG: MockModuleCatalogEntry[] = [
  {
    moduleId: 'SG-AN-IN-STD-32',
    friendlyName: 'Analog Input 32ch Standard',
    technicalName: 'IO731 Analog In',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      inputMode: ['Differential', 'Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['±10 V', '0-10 V', '±5 V'],
      resolution: ['16-bit'],
      speed: ['20 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-AN-IN-PREC-16',
    friendlyName: 'Analog Input 16ch Precision',
    technicalName: 'IO742 Precision Analog In',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['±10 V', '±5 V', '0-20 mA', '4-20 mA'],
      resolution: ['18-bit', '24-bit'],
      speed: ['20 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-AN-IN-HS-64',
    friendlyName: 'Analog Input 64ch High-Speed',
    technicalName: 'IO758 HS Analog In',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 64,
    supportedSpecs: {
      inputMode: ['Differential', 'Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['±10 V', '0-10 V'],
      resolution: ['16-bit', '18-bit'],
      speed: ['100 kHz', '500 kHz'],
    },
  },
  {
    moduleId: 'SG-AN-OUT-STD-32',
    friendlyName: 'Analog Output 32ch Standard',
    technicalName: 'IO761 Analog Out',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      outputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['±10 V', '0-10 V', '±5 V'],
      resolution: ['14-bit', '16-bit'],
      speed: ['20 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-AN-OUT-PREC-16',
    friendlyName: 'Analog Output 16ch Precision',
    technicalName: 'IO773 Precision Analog Out',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      outputMode: ['Differential'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['±10 V', '±5 V', '0-20 mA', '4-20 mA'],
      resolution: ['16-bit', '18-bit'],
      speed: ['20 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-AN-OUT-HS-64',
    friendlyName: 'Analog Output 64ch High-Speed',
    technicalName: 'IO779 HS Analog Out',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 64,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['±10 V', '0-10 V'],
      resolution: ['16-bit', '18-bit'],
      speed: ['100 kHz', '500 kHz'],
    },
  },
  {
    moduleId: 'SG-DI-STD-64',
    friendlyName: 'Digital Input 64ch TTL',
    technicalName: 'IO811 Digital In',
    categoryCoverage: 'digital',
    subCoverage: ['inputs'],
    channelCapacity: 64,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL', '24 V'],
      resolution: ['None', 'Isolated'],
    },
  },
  {
    moduleId: 'SG-DI-ISO-32',
    friendlyName: 'Digital Input 32ch Isolated Power',
    technicalName: 'IO812 Isolated Digital In',
    categoryCoverage: 'digital',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Isolated Power Input'],
      range: ['0-24 V', '0-31 V', '0-48 V'],
      resolution: ['Isolated Inputs'],
    },
  },
  {
    moduleId: 'SG-DI-SER-32',
    friendlyName: 'Digital Input 32ch Serial',
    technicalName: 'IO813 Differential Digital In',
    categoryCoverage: 'digital',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Differential Serial'],
      range: ['RS422/RS485', 'LVDS', 'M-LVDS'],
      resolution: ['None'],
    },
  },
  {
    moduleId: 'SG-DO-STD-64',
    friendlyName: 'Digital Output 64ch TTL',
    technicalName: 'IO821 Digital Out',
    categoryCoverage: 'digital',
    subCoverage: ['outputs'],
    channelCapacity: 64,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL', '24 V'],
      resolution: ['None', 'Isolated'],
      speed: ['Push-pull'],
    },
  },
  {
    moduleId: 'SG-DO-ISO-32',
    friendlyName: 'Digital Output 32ch Isolated Power',
    technicalName: 'IO822 Isolated Digital Out',
    categoryCoverage: 'digital',
    subCoverage: ['outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Isolated Power Output'],
      range: ['+5-34 V', '+5-48 V', '+6-48 V'],
      resolution: ['Isolated Outputs', 'Isolated Inputs + Outputs'],
      speed: ['High-side (0.5 A/ch)', 'Low-side (0.5 A/ch)', 'Selectable HS/LS (1 A/ch)'],
    },
  },
  {
    moduleId: 'SG-DO-SER-32',
    friendlyName: 'Digital Output 32ch Serial Driver',
    technicalName: 'IO823 Differential Digital Out',
    categoryCoverage: 'digital',
    subCoverage: ['outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Differential Serial'],
      range: ['RS422/RS485', 'LVDS', 'M-LVDS'],
      resolution: ['None'],
      speed: ['Driver enabled', 'Driver with line termination'],
    },
  },
  {
    moduleId: 'SG-COMM-MULTI-AUTO',
    friendlyName: 'Automotive Multi-Bus Communication',
    technicalName: 'IO901 Auto Multi Protocol',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 16,
    supportedSpecs: {
      resolution: ['HS CAN', 'HS CAN FD', 'LIN', 'FlexRay', 'SENT', 'PSI5'],
      speed: ['500 kbit/s', '1 Mbit/s', '2 Mbit/s', '5 Mbit/s', '8 Mbit/s', '10 Mbit/s', '19.2 kbit/s'],
    },
    protocolSupport: ['CAN', 'CAN FD', 'LIN', 'FlexRay', 'SENT', 'PSI5', 'XCP over CAN'],
  },
  {
    moduleId: 'SG-COMM-ETH-IND',
    friendlyName: 'Industrial Ethernet Communication',
    technicalName: 'IO902 Industrial Ethernet',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 24,
    supportedSpecs: {
      resolution: ['100BASE-TX', '1000BASE-T', 'Ethernet'],
      speed: ['100 Mbit/s', '1 Gbit/s', '10 Gbit/s'],
    },
    protocolSupport: [
      'EtherCAT',
      'PROFINET',
      'EtherNet/IP',
      'POWERLINK',
      'OPC UA',
      'MQTT',
      'DDS',
      'Raw Ethernet',
      'Real-Time UDP',
      'Modbus TCP',
      'XCP over Ethernet',
      'Automotive Ethernet',
    ],
  },
  {
    moduleId: 'SG-COMM-SERIAL-X',
    friendlyName: 'Serial / Peripheral Communication',
    technicalName: 'IO903 Serial Bus',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 20,
    supportedSpecs: {
      resolution: ['RS-422', 'RS-485', 'RS-232', 'SPI', 'I2C'],
      speed: ['115.2 kbit/s', '400 kbit/s', '1 Mbit/s', '10 Mbit/s', '20 Mbit/s'],
    },
    protocolSupport: ['RS-422', 'RS-485', 'RS-232', 'SPI', 'I2C', 'Modbus RTU', 'PROFIBUS'],
  },
  {
    moduleId: 'SG-COMM-AERO',
    friendlyName: 'Aerospace Communication',
    technicalName: 'IO904 Aero Bus',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 12,
    supportedSpecs: {
      resolution: ['ARINC 429', 'ARINC 629', 'CAN', 'MIL-STD-1553', 'Ethernet'],
      speed: ['100 kbit/s', '1 Mbit/s', '2 Mbit/s', '100 Mbit/s'],
    },
    protocolSupport: ['AFDX (ARINC 664 P7)', 'ARINC 429', 'ARINC 629', 'ARINC 825', 'MIL-STD-1553', 'MVB / WTB'],
  },
  {
    moduleId: 'SG-COMM-TIME',
    friendlyName: 'Timing & Synchronization',
    technicalName: 'IO905 Time Sync',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 8,
    supportedSpecs: {
      resolution: ['Ethernet', 'IRIG', 'GPS'],
      speed: ['Sub-microsecond sync', 'Microsecond sync'],
    },
    protocolSupport: ['PTP (IEEE 1588)', 'IRIG + GPS'],
  },
  {
    moduleId: 'SG-MOT-ENC-32',
    friendlyName: 'Motion Encoder Interface 32ch',
    technicalName: 'IO951 Encoder Interface',
    categoryCoverage: 'motion',
    subCoverage: ['encoder'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['Incremental', 'SSI', 'BiSS', 'EnDat'],
      speed: ['10 kHz', '100 kHz', '1 MHz'],
      resolution: ['16-bit', '24-bit', '32-bit'],
    },
  },
  {
    moduleId: 'SG-MOT-RES-16',
    friendlyName: 'Resolver Interface 16ch',
    technicalName: 'IO952 Resolver Interface',
    categoryCoverage: 'motion',
    subCoverage: ['resolver'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Single-speed', 'Multi-speed'],
      speed: ['2.5 kHz', '5 kHz', '10 kHz'],
      resolution: ['12-bit', '14-bit', '16-bit'],
    },
  },
  {
    moduleId: 'SG-TEMP-MEAS-32',
    friendlyName: 'Temperature Measurement 32ch',
    technicalName: 'IO971 Temperature In',
    categoryCoverage: 'temperature',
    subCoverage: ['measurement'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['Thermocouple', 'RTD', 'Thermistor'],
      speed: ['10 Hz', '100 Hz', '1 kHz'],
    },
  },
  {
    moduleId: 'SG-TEMP-SIM-16',
    friendlyName: 'Temperature Simulation 16ch',
    technicalName: 'IO972 Temperature Out',
    categoryCoverage: 'temperature',
    subCoverage: ['simulation'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Thermocouple', 'RTD', 'Thermistor'],
      speed: ['10 Hz', '100 Hz', '1 kHz'],
    },
  },
  {
    moduleId: 'SG-STRAIN-MIX-24',
    friendlyName: 'Strain & Vibration Mixed 24ch',
    technicalName: 'IO981 Strain IEPE',
    categoryCoverage: 'strain',
    subCoverage: ['strain', 'vibration'],
    channelCapacity: 24,
    supportedSpecs: {
      range: ['Full-Bridge', 'Half-Bridge', 'Quarter-Bridge', '100 mV/g', '500 mV/g', '1000 mV/g'],
      speed: ['1 kHz', '10 kHz', '50 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-FAULT-REL-32',
    friendlyName: 'Fault Insertion Relay 32ch',
    technicalName: 'IO991 Fault Relay',
    categoryCoverage: 'fault',
    subCoverage: ['relays'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['SPST', 'SPDT', 'DPST'],
      speed: ['120 V AC', '250 V AC', '30 V DC'],
    },
  },
  {
    moduleId: 'SG-FAULT-SS-24',
    friendlyName: 'Fault Insertion Solid-State 24ch',
    technicalName: 'IO992 Fault SolidState',
    categoryCoverage: 'fault',
    subCoverage: ['switches'],
    channelCapacity: 24,
    supportedSpecs: {
      range: ['MOSFET', 'IGBT'],
      speed: ['1 A', '5 A', '20 A'],
    },
  },
  {
    moduleId: 'SG-HV-MEAS-16',
    friendlyName: 'High Voltage Measurement 16ch',
    technicalName: 'IO993 HV Measurement',
    categoryCoverage: 'highvoltage',
    subCoverage: ['measurement'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['0–600 V', '0–1000 V', '0–1500 V'],
      speed: ['1 kHz', '10 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-HV-SW-16',
    friendlyName: 'High Voltage Switching 16ch',
    technicalName: 'IO994 HV Switching',
    categoryCoverage: 'highvoltage',
    subCoverage: ['switching'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['IGBT', 'Gate Driver', 'PWM'],
      speed: ['10 kHz', '50 kHz', '100 kHz'],
    },
  },
  {
    moduleId: 'SG-CUSTOM-GP-32',
    friendlyName: 'Custom General Purpose 32ch',
    technicalName: 'IO999 Custom I/O',
    categoryCoverage: 'custom',
    subCoverage: ['gen_purpose'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['Analog In', 'Analog Out', 'Digital I/O'],
      speed: ['Standard', 'High-speed', 'Deterministic'],
    },
  },
]
