export type MockModuleCatalogEntry = {
  moduleId: string
  friendlyName: string
  technicalName: string
  categoryCoverage: string
  subCoverage: string[]
  channelCapacity: number
  supportedSpecs: Record<string, string[]>
  protocolSupport?: string[]
  compatibleMachines?: string[]
}

/**
 * Catalog of Speedgoat I/O modules derived from speedgoat.com product pages.
 *
 * Module IDs follow the real Speedgoat naming convention (IO1xx = analog,
 * IO2xx/IO3xx = digital, IO4xx = resolver/LVDT, IO5xx-IO7xx = communication,
 * IO9xx = temperature simulation / fault insertion / relay).
 *
 * Specs are aligned to the configurator field keys defined in data.ts.
 */
export const MOCK_MODULE_CATALOG: MockModuleCatalogEntry[] = [
  // --- Analog Inputs ---------------------------------------------------------
  {
    moduleId: 'IO131',
    friendlyName: 'Analog Input 16ch +/-10 V Simultaneous',
    technicalName: 'IO131',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO134',
    friendlyName: 'Analog Input 32ch +/-10 V Simultaneous',
    technicalName: 'IO134',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO106',
    friendlyName: 'Analog Input 64ch +/-10 V Simultaneous',
    technicalName: 'IO106',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 64,
    supportedSpecs: {
      inputMode: ['Differential', 'Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO141',
    friendlyName: 'Analog I/O 16+4ch Wide-Range +/-25 V',
    technicalName: 'IO141',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V', '\u00b15 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO142',
    friendlyName: 'Analog I/O 32+8ch Wide-Range +/-25 V',
    technicalName: 'IO142',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V', '\u00b15 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO145',
    friendlyName: 'Analog I/O 16+8ch +/-48 V / Current',
    technicalName: 'IO145',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['\u00b110 V', '\u00b15 V', '0-20 mA', '4-20 mA'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO109',
    friendlyName: 'Analog Input 12ch 24-bit Precision',
    technicalName: 'IO109',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 12,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['24-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO191',
    friendlyName: 'Analog I/O 8+4ch Compact +/-25 V',
    technicalName: 'IO191',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 8,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V', '\u00b15 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO104',
    friendlyName: 'Analog I/O 8+4ch High-Speed 2 MHz',
    technicalName: 'IO104',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 8,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO112',
    friendlyName: 'Analog Input 4-32ch Up to 18-bit 1 MHz',
    technicalName: 'IO112',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit', '18-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO116',
    friendlyName: 'Analog I/O 16+4ch 0-10 V / 0-20 mA Process',
    technicalName: 'IO116',
    categoryCoverage: 'analog',
    subCoverage: ['inputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['0-10 V', '0-20 mA'],
      resolution: ['16-bit'],
      speed: ['20 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO325',
    friendlyName: 'Configurable FPGA Analog I/O 8+4ch',
    technicalName: 'IO325',
    categoryCoverage: 'analog',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 8,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO336',
    friendlyName: 'Configurable FPGA Analog I/O 16+8ch',
    technicalName: 'IO336',
    categoryCoverage: 'analog',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      inputMode: ['Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO397',
    friendlyName: 'Configurable FPGA Analog I/O 4+4ch Compact',
    technicalName: 'IO397',
    categoryCoverage: 'analog',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 4,
    supportedSpecs: {
      inputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  // --- Analog Outputs --------------------------------------------------------
  {
    moduleId: 'IO135',
    friendlyName: 'Analog I/O 32in + 16out Simultaneous',
    technicalName: 'IO135',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO110',
    friendlyName: 'Analog Output 32ch +/-10.8 V',
    technicalName: 'IO110',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['20 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO107',
    friendlyName: 'Analog Output 16ch +/-20 V Simultaneous',
    technicalName: 'IO107',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      outputMode: ['Single-ended', 'Differential'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V', '\u00b15 V'],
      resolution: ['16-bit'],
      speed: ['100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO143',
    friendlyName: 'Analog Output 8ch +/-12 V / 0-24 mA',
    technicalName: 'IO143',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 8,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['\u00b110 V', '0-20 mA'],
      resolution: ['16-bit'],
      speed: ['20 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO144',
    friendlyName: 'Analog Output 16ch +/-12 V / 0-24 mA',
    technicalName: 'IO144',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage', 'Current'],
      signalRange: ['\u00b110 V', '0-20 mA', '4-20 mA'],
      resolution: ['16-bit'],
      speed: ['20 kHz'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO334',
    friendlyName: 'FPGA Analog I/O 16in + 16out 5 MHz',
    technicalName: 'IO334',
    categoryCoverage: 'analog',
    subCoverage: ['outputs'],
    channelCapacity: 16,
    supportedSpecs: {
      outputMode: ['Single-ended'],
      signalType: ['Voltage'],
      signalRange: ['\u00b110 V'],
      resolution: ['16-bit'],
      speed: ['500 kHz'],
    },
    compatibleMachines: ['performance', 'baseline'],
  },
  // --- Digital Inputs --------------------------------------------------------
  {
    moduleId: 'IO203',
    friendlyName: 'Digital I/O 64ch TTL',
    technicalName: 'IO203',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 64,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL'],
      resolution: ['None'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO306',
    friendlyName: 'Configurable Digital I/O 64ch TTL',
    technicalName: 'IO306',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 64,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL'],
      resolution: ['None'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO307',
    friendlyName: 'Configurable Digital 32 TTL + 16 RS422',
    technicalName: 'IO307',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 48,
    supportedSpecs: {
      signalType: ['TTL / Discrete', 'Differential Serial'],
      range: ['5 V TTL', '3.3 V TTL', 'RS422/RS485'],
      resolution: ['None'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO308',
    friendlyName: 'Configurable Digital 32ch RS422/RS485',
    technicalName: 'IO308',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Differential Serial'],
      range: ['RS422/RS485'],
      resolution: ['None'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO292',
    friendlyName: 'Digital I/O 24ch TTL Compact',
    technicalName: 'IO292',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 24,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL'],
      resolution: ['None'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO391',
    friendlyName: 'Configurable Digital 26ch TTL Compact',
    technicalName: 'IO391',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 26,
    supportedSpecs: {
      signalType: ['TTL / Discrete'],
      range: ['5 V TTL', '3.3 V TTL'],
      resolution: ['None'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO206',
    friendlyName: 'Isolated Digital Input 32ch 0-24 V',
    technicalName: 'IO206',
    categoryCoverage: 'digital',
    subCoverage: ['inputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Isolated Power Input'],
      range: ['0-24 V'],
      resolution: ['Isolated Inputs'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO290',
    friendlyName: 'Isolated Digital I/O 8in+8out+8TTL',
    technicalName: 'IO290',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 24,
    supportedSpecs: {
      signalType: ['TTL / Discrete', 'Isolated Power Input', 'Isolated Power Output'],
      range: ['5 V TTL', '0-31 V', '+5-34 V'],
      resolution: ['None', 'Isolated Inputs', 'Isolated Outputs'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO291',
    friendlyName: 'Isolated Digital I/O 8in+8out+8TTL Compact',
    technicalName: 'IO291',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 24,
    supportedSpecs: {
      signalType: ['TTL / Discrete', 'Isolated Power Input', 'Isolated Power Output'],
      range: ['5 V TTL', '0-48 V', '+5-48 V'],
      resolution: ['None', 'Isolated Inputs', 'Isolated Outputs'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO205',
    friendlyName: 'Isolated Digital Output 32ch High-Side 6-48 V',
    technicalName: 'IO205',
    categoryCoverage: 'digital',
    subCoverage: ['outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Isolated Power Output'],
      range: ['+6-48 V'],
      resolution: ['Isolated Outputs'],
      speed: ['High-side (0.5 A/ch)'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO204',
    friendlyName: 'Isolated Digital I/O 16in+16out 0-24 V / 6-48 V',
    technicalName: 'IO204',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 32,
    supportedSpecs: {
      signalType: ['Isolated Power Input', 'Isolated Power Output'],
      range: ['0-24 V', '+6-48 V'],
      resolution: ['Isolated Inputs', 'Isolated Outputs', 'Isolated Inputs + Outputs'],
      speed: ['High-side (0.5 A/ch)', 'Low-side (0.5 A/ch)'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO392',
    friendlyName: 'Configurable 13ch RS422/RS485 Compact',
    technicalName: 'IO392',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 13,
    supportedSpecs: {
      signalType: ['Differential Serial'],
      range: ['RS422/RS485'],
      resolution: ['None'],
      speed: ['Driver enabled'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO394',
    friendlyName: 'Configurable 13ch M-LVDS Compact',
    technicalName: 'IO394',
    categoryCoverage: 'digital',
    subCoverage: ['inputs', 'outputs'],
    channelCapacity: 13,
    supportedSpecs: {
      signalType: ['Differential Serial'],
      range: ['M-LVDS'],
      resolution: ['None'],
      speed: ['Driver enabled'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  // --- Communication Protocols -----------------------------------------------
  {
    moduleId: 'IO603',
    friendlyName: 'CAN FD / LIN / XCP 4-port',
    technicalName: 'IO603',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 4,
    supportedSpecs: {
      resolution: ['HS CAN', 'HS CAN FD', 'LIN'],
      speed: ['500 kbit/s', '1 Mbit/s', '2 Mbit/s', '5 Mbit/s', '8 Mbit/s', '19.2 kbit/s'],
    },
    protocolSupport: ['CAN', 'CAN FD', 'LIN', 'XCP over CAN'],
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO601',
    friendlyName: 'CAN / LIN / XCP 2-port',
    technicalName: 'IO601',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 2,
    supportedSpecs: {
      resolution: ['HS CAN', 'LIN'],
      speed: ['500 kbit/s', '1 Mbit/s', '19.2 kbit/s'],
    },
    protocolSupport: ['CAN', 'LIN', 'XCP over CAN'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO691',
    friendlyName: 'CAN / XCP 2-port Compact',
    technicalName: 'IO691',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 2,
    supportedSpecs: {
      resolution: ['HS CAN'],
      speed: ['500 kbit/s', '1 Mbit/s'],
    },
    protocolSupport: ['CAN', 'XCP over CAN'],
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO623',
    friendlyName: 'FlexRay 4-port',
    technicalName: 'IO623',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 4,
    supportedSpecs: {
      resolution: ['FlexRay'],
      speed: ['10 Mbit/s'],
    },
    protocolSupport: ['FlexRay'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO624',
    friendlyName: 'PSI5 8-port',
    technicalName: 'IO624',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 8,
    supportedSpecs: {
      resolution: ['PSI5'],
      speed: ['125 kbit/s', '189 kbit/s'],
    },
    protocolSupport: ['PSI5'],
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO723',
    friendlyName: 'Automotive Ethernet + CAN FD Multi-Bus 6-port',
    technicalName: 'IO723',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 6,
    supportedSpecs: {
      resolution: ['HS CAN', 'HS CAN FD', '100BASE-T1', '1000BASE-T1'],
      speed: ['500 kbit/s', '1 Mbit/s', '2 Mbit/s', '5 Mbit/s', '100 Mbit/s', '1 Gbit/s'],
    },
    protocolSupport: ['CAN', 'CAN FD', 'Automotive Ethernet'],
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO750',
    friendlyName: 'EtherCAT Master',
    technicalName: 'IO750',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['100BASE-TX'],
      speed: ['100 Mbit/s'],
    },
    protocolSupport: ['EtherCAT'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO751',
    friendlyName: 'PROFINET Controller',
    technicalName: 'IO751',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['100BASE-TX'],
      speed: ['100 Mbit/s'],
    },
    protocolSupport: ['PROFINET'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  {
    moduleId: 'IO755',
    friendlyName: 'EtherNet/IP Adapter',
    technicalName: 'IO755',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['100BASE-TX'],
      speed: ['100 Mbit/s'],
    },
    protocolSupport: ['EtherNet/IP'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  {
    moduleId: 'IO758',
    friendlyName: 'POWERLINK Controller',
    technicalName: 'IO758',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['100BASE-TX'],
      speed: ['100 Mbit/s'],
    },
    protocolSupport: ['POWERLINK'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  {
    moduleId: 'IO715',
    friendlyName: 'Multi-Protocol Ethernet 4-port GbE',
    technicalName: 'IO715',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 4,
    supportedSpecs: {
      resolution: ['100BASE-TX', '1000BASE-T', 'Ethernet'],
      speed: ['100 Mbit/s', '1 Gbit/s'],
    },
    protocolSupport: [
      'EtherCAT',
      'Real-Time UDP',
      'XCP over Ethernet',
      'Modbus TCP',
      'OPC UA',
      'MQTT',
      'DNP3',
      'IEC 61850',
    ],
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO717',
    friendlyName: 'Multi-Protocol Ethernet 2-port 10 GbE',
    technicalName: 'IO717',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 2,
    supportedSpecs: {
      resolution: ['1000BASE-T', 'Ethernet'],
      speed: ['1 Gbit/s', '10 Gbit/s'],
    },
    protocolSupport: [
      'EtherCAT',
      'Real-Time UDP',
      'XCP over Ethernet',
      'Modbus TCP',
      'OPC UA',
      'Raw Ethernet',
    ],
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO791',
    friendlyName: 'Multi-Protocol Ethernet 2-port Compact',
    technicalName: 'IO791',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 2,
    supportedSpecs: {
      resolution: ['100BASE-TX', '1000BASE-T', 'Ethernet'],
      speed: ['100 Mbit/s', '1 Gbit/s'],
    },
    protocolSupport: ['EtherNet/IP', 'Modbus TCP', 'OPC UA', 'DNP3', 'IEC 61850', 'MQTT'],
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO641',
    friendlyName: 'PROFIBUS DP Master',
    technicalName: 'IO641',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['RS-485'],
      speed: ['12 Mbit/s'],
    },
    protocolSupport: ['PROFIBUS'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  {
    moduleId: 'IO643',
    friendlyName: 'CANopen Master',
    technicalName: 'IO643',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['CAN'],
      speed: ['500 kbit/s', '1 Mbit/s'],
    },
    protocolSupport: ['CANopen'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  {
    moduleId: 'IO503',
    friendlyName: 'Serial RS-422/485/232 4-port',
    technicalName: 'IO503',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 4,
    supportedSpecs: {
      resolution: ['RS-422', 'RS-485', 'RS-232'],
      speed: ['115.2 kbit/s', '1 Mbit/s'],
    },
    protocolSupport: ['RS-422', 'RS-485', 'RS-232', 'Modbus RTU'],
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO581',
    friendlyName: 'Serial RS-422/485/232 4-port Compact',
    technicalName: 'IO581',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 4,
    supportedSpecs: {
      resolution: ['RS-422', 'RS-485', 'RS-232'],
      speed: ['115.2 kbit/s', '1 Mbit/s', '10 Mbit/s'],
    },
    protocolSupport: ['RS-422', 'RS-485', 'RS-232', 'Modbus RTU'],
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO682',
    friendlyName: 'ARINC 429 / 629 Multi-Channel',
    technicalName: 'IO682',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 16,
    supportedSpecs: {
      resolution: ['ARINC 429', 'ARINC 629'],
      speed: ['100 kbit/s', '2 Mbit/s'],
    },
    protocolSupport: ['ARINC 429', 'ARINC 629', 'ARINC 825'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO781',
    friendlyName: 'AFDX / ARINC 664 Part 7 GbE',
    technicalName: 'IO781',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 2,
    supportedSpecs: {
      resolution: ['Ethernet'],
      speed: ['100 Mbit/s', '1 Gbit/s'],
    },
    protocolSupport: ['AFDX (ARINC 664 P7)'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO619',
    friendlyName: 'MVB / WTB Gateway',
    technicalName: 'IO619',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 32,
    supportedSpecs: {
      resolution: ['MVB / WTB'],
      speed: ['1.5 Mbit/s'],
    },
    protocolSupport: ['MVB / WTB'],
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO753',
    friendlyName: 'Modbus TCP Gateway',
    technicalName: 'IO753',
    categoryCoverage: 'communication',
    subCoverage: ['protocols'],
    channelCapacity: 1,
    supportedSpecs: {
      resolution: ['Ethernet'],
      speed: ['100 Mbit/s'],
    },
    protocolSupport: ['Modbus TCP'],
    compatibleMachines: ['performance', 'baseline', 'mobile', 'unit'],
  },
  // --- Motion & Position: Encoders -------------------------------------------
  {
    moduleId: 'IO3xx-Enc',
    friendlyName: 'Configurable FPGA Encoder Interface',
    technicalName: 'IO3xx (Encoder config)',
    categoryCoverage: 'motion',
    subCoverage: ['encoder'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Incremental', 'SSI', 'BiSS', 'EnDat'],
      speed: ['10 kHz', '100 kHz', '1 MHz'],
      resolution: ['16-bit', '24-bit', '32-bit'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  // --- Motion & Position: Resolvers ------------------------------------------
  {
    moduleId: 'IO424',
    friendlyName: 'LVDT / RVDT / Synchro / Resolver Measurement',
    technicalName: 'IO424',
    categoryCoverage: 'motion',
    subCoverage: ['resolver'],
    channelCapacity: 8,
    supportedSpecs: {
      range: ['Single-speed', 'Multi-speed'],
      speed: ['2.5 kHz', '5 kHz', '10 kHz'],
      resolution: ['12-bit', '14-bit', '16-bit'],
    },
    compatibleMachines: ['performance', 'pulse', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO425',
    friendlyName: 'LVDT / RVDT / Resolver Emulation',
    technicalName: 'IO425',
    categoryCoverage: 'motion',
    subCoverage: ['resolver'],
    channelCapacity: 8,
    supportedSpecs: {
      range: ['Single-speed', 'Multi-speed'],
      speed: ['2.5 kHz', '5 kHz', '10 kHz'],
      resolution: ['12-bit', '14-bit', '16-bit'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO3xx-Res',
    friendlyName: 'Configurable FPGA Resolver Measurement',
    technicalName: 'IO3xx (Resolver config)',
    categoryCoverage: 'motion',
    subCoverage: ['resolver'],
    channelCapacity: 4,
    supportedSpecs: {
      range: ['Single-speed'],
      speed: ['5 kHz', '10 kHz'],
      resolution: ['12-bit', '14-bit'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  // --- Temperature -----------------------------------------------------------
  {
    moduleId: 'IO171',
    friendlyName: 'Thermocouple / RTD / Strain Measurement 16ch',
    technicalName: 'IO171',
    categoryCoverage: 'temperature',
    subCoverage: ['measurement'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Thermocouple', 'RTD', 'Thermistor'],
      speed: ['10 Hz', '100 Hz', '1 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'unit'],
  },
  {
    moduleId: 'IO172',
    friendlyName: 'RTD / Thermocouple / Strain Measurement 6ch Compact',
    technicalName: 'IO172',
    categoryCoverage: 'temperature',
    subCoverage: ['measurement'],
    channelCapacity: 6,
    supportedSpecs: {
      range: ['Thermocouple', 'RTD'],
      speed: ['10 Hz', '100 Hz'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
  {
    moduleId: 'IO975',
    friendlyName: 'Thermocouple Simulator 32ch',
    technicalName: 'IO975',
    categoryCoverage: 'temperature',
    subCoverage: ['simulation'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['Thermocouple'],
      speed: ['10 Hz', '100 Hz', '1 kHz'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO970',
    friendlyName: 'RTD (PT100/PT1000) Simulator 18ch',
    technicalName: 'IO970',
    categoryCoverage: 'temperature',
    subCoverage: ['simulation'],
    channelCapacity: 18,
    supportedSpecs: {
      range: ['RTD'],
      speed: ['10 Hz', '100 Hz', '1 kHz'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO925',
    friendlyName: 'Thermistor Simulator (Precision Resistor) 18ch',
    technicalName: 'IO925',
    categoryCoverage: 'temperature',
    subCoverage: ['simulation'],
    channelCapacity: 18,
    supportedSpecs: {
      range: ['Thermistor'],
      speed: ['10 Hz', '100 Hz'],
    },
    compatibleMachines: ['performance'],
  },
  // --- Strain & Vibration ----------------------------------------------------
  {
    moduleId: 'IO972',
    friendlyName: 'Strain Gauge Simulator 6ch',
    technicalName: 'IO972',
    categoryCoverage: 'strain',
    subCoverage: ['strain'],
    channelCapacity: 6,
    supportedSpecs: {
      range: ['Full-Bridge', 'Half-Bridge', 'Quarter-Bridge'],
      speed: ['1 kHz', '10 kHz'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO171-Strain',
    friendlyName: 'Strain Gauge Measurement (via IO171) 16ch',
    technicalName: 'IO171 (Strain)',
    categoryCoverage: 'strain',
    subCoverage: ['strain'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Full-Bridge', 'Half-Bridge', 'Quarter-Bridge'],
      speed: ['1 kHz', '10 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'unit'],
  },
  {
    moduleId: 'IO112-IEPE',
    friendlyName: 'Vibration (IEPE) Measurement via IO112 18-bit',
    technicalName: 'IO112 (IEPE)',
    categoryCoverage: 'strain',
    subCoverage: ['vibration'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['100 mV/g', '500 mV/g', '1000 mV/g'],
      speed: ['10 kHz', '50 kHz', '100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  // --- Fault Insertion & Relay Switching --------------------------------------
  {
    moduleId: 'IO94x',
    friendlyName: 'Relay Switching Module (Reed & Electromechanical)',
    technicalName: 'IO94x',
    categoryCoverage: 'fault',
    subCoverage: ['relays'],
    channelCapacity: 32,
    supportedSpecs: {
      range: ['SPST', 'SPDT', 'DPST'],
      speed: ['120 V AC', '250 V AC', '30 V DC'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'IO98x',
    friendlyName: 'Fault Insertion Module up to 75ch',
    technicalName: 'IO98x',
    categoryCoverage: 'fault',
    subCoverage: ['switches'],
    channelCapacity: 75,
    supportedSpecs: {
      range: ['MOSFET', 'IGBT'],
      speed: ['1 A', '5 A', '20 A'],
    },
    compatibleMachines: ['performance'],
  },
  {
    moduleId: 'FIU-BMS',
    friendlyName: 'Fault Insertion Unit for BMS 36ch',
    technicalName: 'Fault Insertion Unit (BMS)',
    categoryCoverage: 'fault',
    subCoverage: ['switches', 'relays'],
    channelCapacity: 36,
    supportedSpecs: {
      range: ['MOSFET'],
      speed: ['1 A', '5 A'],
    },
    compatibleMachines: ['performance', 'mobile', 'baseline', 'unit'],
  },
  // --- High Voltage ----------------------------------------------------------
  {
    moduleId: 'IO145-HV',
    friendlyName: 'High Voltage Analog Measurement +/-48 V',
    technicalName: 'IO145 (HV mode)',
    categoryCoverage: 'highvoltage',
    subCoverage: ['measurement'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['0\u2013600 V'],
      speed: ['1 kHz', '10 kHz', '100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO334-PWM',
    friendlyName: 'FPGA High-Speed PWM / Gate Driver 16ch',
    technicalName: 'IO334 (PWM mode)',
    categoryCoverage: 'highvoltage',
    subCoverage: ['switching'],
    channelCapacity: 16,
    supportedSpecs: {
      range: ['Gate Driver', 'PWM'],
      speed: ['10 kHz', '50 kHz', '100 kHz'],
    },
    compatibleMachines: ['performance', 'baseline'],
  },
  // --- Custom / General Purpose ----------------------------------------------
  {
    moduleId: 'IO324',
    friendlyName: 'Configurable FPGA Mixed I/O 32AI+8AO+32DIO',
    technicalName: 'IO324',
    categoryCoverage: 'custom',
    subCoverage: ['gen_purpose'],
    channelCapacity: 72,
    supportedSpecs: {
      range: ['Analog In', 'Analog Out', 'Digital I/O'],
      speed: ['Standard', 'High-speed', 'Deterministic'],
    },
    compatibleMachines: ['performance', 'baseline', 'mobile'],
  },
  {
    moduleId: 'IO397-GP',
    friendlyName: 'Configurable FPGA Mixed I/O 4AI+4AO+14DIO Compact',
    technicalName: 'IO397 (mixed)',
    categoryCoverage: 'custom',
    subCoverage: ['gen_purpose'],
    channelCapacity: 22,
    supportedSpecs: {
      range: ['Analog In', 'Analog Out', 'Digital I/O'],
      speed: ['Standard', 'High-speed'],
    },
    compatibleMachines: ['baseline', 'unit'],
  },
]
